### ISSUE TITLE
1.4.3. 缓存this

### ISSUE THREAD

**Issue by greatghoul** [i5ting/How-to-write-jQuery-plugin#3]
``` javascript
// 将defaults 和 options 参数合并到{}
var obj = $(this);
$(obj).find(....);
```

`obj` 已经是 jQuery Object 了，再使用 `$(obj)` 就没有必要了，这样反倒没有起到缓存的作用。

**Comment by i5ting** [comment]
嗯，你说的是对的，不过给每个对象增加$(obj)属于防御性写法，保证对象一定是jq对象，cache是说jquery的this是指代上下文，上下文变换的时候，this就找不到了

已更新对应章节，欢迎review
